AllCops:
  Exclude:
    - 'Guardfile'
    - 'Gemfile'

Style/ClassAndModuleChildren:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 9
Style/MultilineOperationIndentation:
  Enabled: false

Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 35
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 13
Metrics/AbcSize:
  Enabled: false
