AllCops:
  Exclude:
    - '**/metadata.rb'
    - '**/*.gemspec'
    - '**/version.rb'
    - '*file'

Style/ClassAndModuleChildren:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 9
Style/MultilineOperationIndentation:
  Enabled: false

Metrics/LineLength:
  Max: 202
Metrics/MethodLength:
  Max: 35
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 13
Metrics/AbcSize:
  Enabled: false
Metrics/ParameterLists:
  Max: 6